---
title: "Hocket_tests"
output: html_document
date: "2025-02-12"
---

```{r setup}
df <- read.csv("Hockey_Scores.csv")
```

```{r library}
library(dplyr)
library(lubridate)
library(tidyr)
library(ggplot2)
```

```{r}
#Change later, these are just for testing right now
eval_types <- c("Skating", "Shooting", "Passing", "Puck Handling", 
                "Hockey Sense", "Hockey IQ", "Puck Control", "Positioning", "Overall Ranking")

filter_scores <- df %>%
  filter(Name %in% eval_types)

```

```{r}
player_scores <- filter_scores %>%
  group_by(Player.Id) %>%
  summarise(Value = list(Value), Name = list(Name)) %>%
  unnest(cols = c(Value, Name))

player_981 <- player_scores %>%
  filter(Player.Id == 1148740)

print(player_981)

```

```{r}
#Fix to the Date
filter_scores$Score.Date <- as.Date(filter_scores$Score.Date)
filter_scores$Birthdate <- as.Date(filter_scores$Birthdate)

#pull the year
filter_scores$Score.Year <- format(filter_scores$Score.Date, "%Y")

#Calculate the age at evaluations
filter_scores$Age <- as.numeric(filter_scores$Score.Year) - as.numeric(format(filter_scores$Birthdate, "%Y"))


```

```{r}
#Separate the score by year so that players evaluated over different years are seperate entity
separate_scores <- filter_scores %>%
  arrange(Player.Id, Score.Year, Name)

head(separate_scores)
```
```{r}
age_freq <- table(separate_scores$Age)
age_freq <- sort(age_freq, decreasing = TRUE)
print(age_freq)

filter_age <- separate_scores %>%
  filter(Age >= 9 & Age <= 18)
```
```{r}
ggplot(filter_age, aes(x = factor(Age))) +
  geom_bar(fill = "grey") +
  labs(title = "Age Frequency", x = "Age", y = "Count") +
  theme_minimal()
```
```{r}
corr_data <- filter_age %>%
  spread(key = Name, value = Value)

corr_matrix <- cor(corr_data[, -1])


```



















