---
title: "testing_2"
output: html_document
date: "2025-02-20"
---

```{r setup, include=FALSE}
train <- read.csv("train.csv")

test <- read.csv("test.csv")
```

```{r library}
library(dplyr)
library(ggplot2)
library(caret)
library(randomForest)
library(xgboost)
```

```{r classes}

#do this for test set
train <- train %>%
  mutate(Value = as.numeric(Value))

groups <- quantile(train$Value, probs = c(0.2, 0.4, 0.6, 0.8), na.rm = TRUE)

# 1 being below average and 5 being above average
train <- train %>%
  mutate(ranking = case_when(
    Value >= groups[4] ~ "5",
    Value >= groups[3] ~ "4",
    Value >= groups[2] ~ "3",
    Value >= groups[1] ~ "2",
    TRUE ~ "1"
  ))

train$ranking <- factor(train$ranking, levels = c("1", "2", "3", "4", "5"))
table(train$ranking)

test <- test %>%
  mutate(Value = as.numeric(Value))

groups <- quantile(test$Value, probs = c(0.2, 0.4, 0.6, 0.8), na.rm = TRUE)

# 1 being below average and 5 being above average
test <- test %>%
  mutate(ranking = case_when(
    Value >= groups[4] ~ "5",
    Value >= groups[3] ~ "4",
    Value >= groups[2] ~ "3",
    Value >= groups[1] ~ "2",
    TRUE ~ "1"
  ))

test$ranking <- factor(test$ranking, levels = c("1", "2", "3", "4", "5"))
table(test$ranking)
```
```{r visual}
ggplot(train, aes(x = ranking, fill = ranking)) +
  geom_bar() +
  labs(title = "Player Rankings Distribution", x = "Ranking", y = "num") +
  theme_minimal()

```
```{r train model(random forest)}
set.seed(12345)

train <- na.omit(train)

model <- randomForest(ranking ~ Value + Name, data = train, importance = TRUE)

print(model)
```
```{r train model(xgboost)}
set.seed(12345)

train$ranking <- as.numeric(train$ranking)

train_matrix <- as.matrix(select(train, -Player.Id, -ranking))

train_label <- train$ranking

xgb_train <-  xgb.DMatrix(data = train_matrix, label = train_label)

test$ranking <- as.numeric(test$ranking)

test_matrix <- as.matrix(select(test, -Player.Id, -ranking))

test_label <- test$ranking

xgb_test <-  xgb.DMatrix(data = test_matrix, label = test_label)
```


















